name: Version Release
description: Submit a new version release for a specific branch
title: "[RELEASE] - "
labels: ["release"]
body:
  - type: dropdown
    id: branch
    attributes:
      label: Branch
      description: Select the branch this release is for
      options:
        - MAF
        - MAIT
        - Australia
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Current status of the release
      options:
        - Todo
        - In Progress
        - Done
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Enter the release version (e.g. 1.2.3)
      placeholder: "1.2.3"
    validations:
      required: true
