name: "Customer Version Update"
description: "Update customer version information"
title: "[Version]: "
labels: ["version-update"]
body:
  - type: markdown
    attributes:
      value: "## Customer Version Update Form"

  - type: input
    id: customer-name
    attributes:
      label: "Customer Name"
      description: "Customer receiving this update"
      placeholder: "Acme Corp"
    validations:
      required: true

  - type: input
    id: version-number
    attributes:
      label: "Version"
      description: "Version number"
      placeholder: "v1.2.3"
    validations:
      required: true

  - type: input
    id: release-date
    attributes:
      label: "Date"
      description: "Release date"
      placeholder: "YYYY-MM-DD"
    validations:
      required: true
