name: Sync Version Release to Project

on:
  issues:
    types: [opened]

jobs:
  sync-release:
    runs-on: ubuntu-latest

    steps:
      - name: Extract issue body
        id: extract
        run: |
          echo "ISSUE_BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Parse form fields
        id: parse
        run: |
          BRANCH=$(echo "$ISSUE_BODY" | grep -A1 '### Branch' | tail -n1 | xargs)
          STATUS=$(echo "$ISSUE_BODY" | grep -A1 '### Status' | tail -n1 | tr -d '\r' | xargs)
          STATUS_LOWER=$(echo "$STATUS" | tr '[:upper:]' '[:lower:]')
          echo "status=$STATUS_LOWER" >> $GITHUB_OUTPUT

          VERSION=$(echo "$ISSUE_BODY" | grep -A1 '### Version' | tail -n1 | xargs)
          REPO="${{ github.repository }}"

          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "status=$STATUS" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "repository=$REPO" >> $GITHUB_OUTPUT

      - name: Skip if not Done
        if: steps.parse.outputs.status != 'Done'
        run: echo "Status is not Done. Exiting."

      - name: Sync with GitHub Project (VersionReleases)
        if: steps.parse.outputs.status == 'done'
        uses: actions/github-script@v7
        env:
          GH_TOKEN: ${{ secrets.PROJECTS_PAT }}
        with:
          script: |
            const repo = '${{ steps.parse.outputs.repository }}';
            const branch = '${{ steps.parse.outputs.branch }}';
            const version = '${{ steps.parse.outputs.version }}';
            const status = '${{ steps.parse.outputs.status }}';
            const org = 'Adama-com';
            const projectNumber = 1; // Update this if VersionReleases is a different number

            const { graphql } = require('@octokit/graphql');
            const gql = graphql.defaults({
              headers: {
                authorization: `token ${process.env.GH_TOKEN}`,
              },
            });

            const projectData = await gql(`
              query {
                organization(login: "${org}") {
                  projectV2(number: ${projectNumber}) {
                    id
                    fields(first: 20) {
                      nodes {
                        id
                        name
                        dataType
                        ... on ProjectV2SingleSelectField {
                          options {
                            id
                            name
                          }
                        }
                      }
                    }
                    items(first: 100) {
                      nodes {
                        id
                        content {
                          ... on Issue {
                            title
                            repository {
                              nameWithOwner
                            }
                          }
                        }
                        fieldValues(first: 10) {
                          nodes {
                            ... on ProjectV2ItemFieldSingleSelectValue {
                              field {
                                ... on ProjectV2SingleSelectField {
                                  name
                                }
                              }
                              option {
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            `);

            const project = projectData.organization.projectV2;
            const fields = project.fields.nodes;
            const fieldMap = Object.fromEntries(fields.map(f => [f.name, f]));

            function getOptionId(fieldName, value) {
              const field = fieldMap[fieldName];
              return field?.options?.find(opt => opt.name === value)?.id || null;
            }

            const match = project.items.nodes.find(item =>
              item.content?.repository?.nameWithOwner === repo &&
              item.fieldValues.nodes.some(f =>
                f.field?.name === "Branch" && f.option?.name === branch
              )
            );

            async function updateFields(itemId) {
              for (const [fieldName, value] of Object.entries({
                "Branch": branch,
                "Current Version": version,
                "Status": status,
                "Repository": repo
              })) {
                const field = fieldMap[fieldName];
                if (!field) continue;

                const input = {
                  projectId: project.id,
                  itemId: itemId,
                  fieldId: field.id,
                  value: {}
                };

                if (field.dataType === 'SINGLE_SELECT') {
                  const optionId = getOptionId(fieldName, value);
                  if (!optionId) continue;
                  input.value.singleSelectOptionId = optionId;
                } else if (field.dataType === 'TEXT') {
                  input.value.text = value;
                }

                await gql(`
                  mutation($input: UpdateProjectV2ItemFieldValueInput!) {
                    updateProjectV2ItemFieldValue(input: $input) {
                      projectV2Item {
                        id
                      }
                    }
                  }
                `, { input });
              }
            }

            if (match) {
              console.log("Item found — updating");
              await updateFields(match.id);
            } else {
              console.log("No match — creating new item");
              const newItem = await gql(`
                mutation {
                  addProjectV2ItemById(input: {
                    projectId: "${project.id}",
                    contentId: "${{ github.event.issue.node_id }}"
                  }) {
                    item {
                      id
                    }
                  }
                }
              `);
              await updateFields(newItem.addProjectV2ItemById.item.id);
            }
