name: Sync Version Release to Project

on:
  issues:
    types: [opened]

jobs:
  sync-release:
    runs-on: ubuntu-latest

    steps:
      - name: Extract issue body
        id: extract
        run: |
          echo "ISSUE_BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Parse form fields
        id: parse
        run: |
          BRANCH=$(echo "$ISSUE_BODY" | grep -A1 '### Branch' | tail -n1 | xargs)
          STATUS=$(echo "$ISSUE_BODY" | awk '/### Status/{getline; while($0 ~ /^$/) { getline }; print $0 }' | xargs)
          STATUS_LOWER=$(echo "$STATUS" | tr '[:upper:]' '[:lower:]')
          VERSION=$(echo "$ISSUE_BODY" | grep -A1 '### Version' | tail -n1 | xargs)
          REPO="${{ github.repository }}"
          
          # Print the values for debugging
          echo "Branch: $BRANCH"
          echo "Status: $STATUS"
          echo "Version: $VERSION"
          echo "Repository: $REPO"
          
          # Set outputs
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
          echo "status=$STATUS_LOWER" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "repository=$REPO" >> $GITHUB_OUTPUT

      - name: Skip if not Done
        if: steps.parse.outputs.status != 'done'
        run: echo "Status is not Done. Exiting."

      - name: Add Comment to Issue
        if: steps.parse.outputs.status == 'done'
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            // Use String() to ensure we get a string even if the value is empty or undefined
            const branch = String('${{ steps.parse.outputs.branch }}');
            const version = String('${{ steps.parse.outputs.version }}');
            const status = String('${{ steps.parse.outputs.status }}');
            const repo = String('${{ steps.parse.outputs.repository }}');
            
            console.log('Values received:');
            console.log(`Branch: "${branch}"`);
            console.log(`Version: "${version}"`);
            console.log(`Status: "${status}"`);
            console.log(`Repository: "${repo}"`);
            
            // Create comment body
            const commentBody = `
            # Version Release Sync
            
            This issue has been processed by the Version Release Sync workflow with the following details:
            
            - **Branch:** ${branch}
            - **Version:** ${version}
            - **Status:** ${status}
            - **Repository:** ${repo}
            
            Since automatic project syncing encountered authorization issues, please manually add this to the appropriate project.
            `;
            
            // Add comment to the issue
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: commentBody
            });
            
            console.log('Added comment to issue #' + context.issue.number);
            
            // Try to create a label to indicate status
            try {
              // First check if the label exists
              const statusLabel = `status:${status.toLowerCase().replace(/\s+/g, '-')}`;
              
              try {
                // Try to get the label
                await github.rest.issues.getLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: statusLabel
                });
                
                console.log(`Label ${statusLabel} exists. Adding to issue...`);
              } catch (error) {
                // Label doesn't exist, create it
                console.log(`Label ${statusLabel} doesn't exist. Creating...`);
                
                // Generate a color based on status
                let color = '0075ca'; // default blue
                if (status.toLowerCase().includes('done')) {
                  color = '0e8a16'; // green
                } else if (status.toLowerCase().includes('progress')) {
                  color = 'fbca04'; // yellow
                }
                
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: statusLabel,
                  color: color,
                  description: `Issue with status: ${status}`
                });
                
                console.log(`Created label ${statusLabel}`);
              }
              
              // Add the label to the issue
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: [statusLabel]
              });
              
              console.log(`Added label ${statusLabel} to issue #${context.issue.number}`);
            } catch (error) {
              console.log(`Error handling labels: ${error.message}`);
            }
            
            // Try to use GraphQL to add to Projects v2 (one final attempt)
            try {
              console.log("Attempting to add to projects via GraphQL...");
              
              // First, get the organization's projects
              const projectsQuery = `
                query {
                  organization(login: "${context.repo.owner}") {
                    projectsV2(first: 10) {
                      nodes {
                        id
                        title
                        number
                      }
                    }
                  }
                }
              `;
              
              const projectsResult = await github.graphql(projectsQuery);
              console.log("Projects result:", JSON.stringify(projectsResult, null, 2));
              
              // If we have projects, try to add the issue to the first one
              if (projectsResult.organization.projectsV2.nodes.length > 0) {
                const project = projectsResult.organization.projectsV2.nodes[0];
                console.log(`Found project: ${project.title} (#${project.number})`);
                
                // Add the issue to the project
                const addMutation = `
                  mutation {
                    addProjectV2ItemById(input: {
                      projectId: "${project.id}",
                      contentId: "${context.payload.issue.node_id}"
                    }) {
                      item {
                        id
                      }
                    }
                  }
                `;
                
                const addResult = await github.graphql(addMutation);
                console.log("Add result:", JSON.stringify(addResult, null, 2));
                
                if (addResult.addProjectV2ItemById.item.id) {
                  console.log(`Successfully added issue to project ${project.title}`);
                  
                  // Add a comment mentioning the project
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: context.issue.number,
                    body: `✅ **Success:** This issue has been automatically added to project "${project.title}" (#${project.number}).`
                  });
                }
              }
            } catch (error) {
              console.log("Failed to add to project via GraphQL:", error.message);
              
              // Add a final notification summarizing what happened
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `📌 **Workflow Summary:** Added detailed comment and applied status label. Please manually add this issue to your project tracking board.`
              });
            }
